version: '3.7'

networks:
  logstash:
    external: true
    name: localdev

services:
  web:
    build:
      context: .
      args:
        env: prod
    container_name: logstash-aws
    networks:
      - logstash
    restart: on-failure
    volumes:
      - ./conf/es.conf:/opt/es.conf
      - ./conf/mysql-connector-java-8.0.13.jar:/opt/mysql-connector-java-8.0.13.jar
    env_file:
      - ./conf/prod/prod.env
